version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm run dev"
