version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      - "2002:20"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm run dev"
