version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
      - "2222:22"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
