name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main # Change this to your default branch
    paths:
      - 'shop/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@93.127.195.116 << 'EOF'
            cd Multivendor-marketplace/shop

            # Pull the latest code from Git
            git pull

            # Delete the pm2 process named "publisher" if it exists
            pm2 delete advertiser || echo "No process named 'advertiser' to delete."

            npm run build

            # Start the application with pm2 under the name "advertiser"
            pm2 start npm --name "advertiser" -- run start

            # Save the pm2 process list
            pm2 save
          EOF
