name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main # Change this to your default branch
    paths:
      - 'shop/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@93.127.195.116 'cd Multivendor-marketplace/shop  && git pull && npm run dev'
